### ISSUE TITLE
can't import

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [sickmartian/CalendarView#1]
![image](https://user-images.githubusercontent.com/5357526/31931752-e0eb9162-b8ac-11e7-99b5-a893bc0f331f.png)

**Comment by sickmartian** [comment]
Hi, did you clone with the recursive flag ?
try again with: `git clone --recursive https://github.com/sickmartian/CalendarView.git`

**Comment by AndroidDeveloperLB** [comment]
I cloned normally, like I do for every repo, using TortoiseGit.
Still same issue. Here's to show that all files are there:

![image](https://user-images.githubusercontent.com/5357526/31943384-3e47ffde-b8d1-11e7-8a24-472912910c6a.png)

**Comment by sickmartian** [comment]
Uhm, I don't know TortoiseGit, is there a flag for recursive maybe in the advanced options?
You are missing the library, the calendarview directory at the root should have some files and it doesn't show the plus sign at the left in Android Studio so I'm guessing that is empty.

The library lives at https://github.com/sickmartian/CalendarViewLib and is referenced via submodules, maybe you have an option to initialize and update a submodule ? in a git console I think you would do something like `git submodule init` and then `git submodule update` with the repository as it is now.

**Comment by AndroidDeveloperLB** [comment]
Oh, this makes sense. It has this checkbox:
![image](https://user-images.githubusercontent.com/5357526/31944937-60f29c9c-b8d6-11e7-90b3-2991cd196b52.png)

ok, I've cloned it this way, and I can see the library folder not empty, but now I got this error:

![image](https://user-images.githubusercontent.com/5357526/31944994-8f37e846-b8d6-11e7-8c84-f1cff914bb6b.png)

I've updated everything that's possible, and also commented the "clean" part:

```
//task clean(type: Delete) {
//    delete rootProject.buildDir
//}
```

And now it works fine.
Please fix the repo.

**Comment by sickmartian** [comment]
Hi, thanks for the heads up! I haven't updated it in a while and it seems like AS / gradle is complaining of something new, I will try and figure out what that was for o.O

**Comment by AndroidDeveloperLB** [comment]
Wait, why close it then...

**Comment by sickmartian** [comment]
Well, the issue was that you couldn't import because of the recursive flag in git, so I'm closing that as solved. The gradle thingy it's another different thing I will take a look at whenever I have the chance to and you solved it for yourself in the meantime.

**Comment by AndroidDeveloperLB** [comment]
Thought it can be a reminder.
ok.
