### ISSUE TITLE
How to slide to choose any date?

### ISSUE THREAD

**Issue by hamurcuabi** [sickmartian/CalendarView#2]
is tehre any methode to slide ?

**Comment by sickmartian** [comment]
uhm, no, what I do is put several instances of the view on a view pager.. I think I ended up using a custom subclass of FragmentStatePagerAdapter to be able to switch between month and week views without taking up all the memory.

**Comment by hamurcuabi** [comment]
it is a good idea ı am gonna try it thanks alot :)
